### ISSUE TITLE
Reading client id from .Renviron Reading client secret from .Renviron Auto-refreshing stale OAuth token. Error in refresh_oauth2.0(self$endpoint, self$app, self$credentials) :    client error: (400) Bad Request

### ISSUE THREAD

**Issue by austintrombley** [brendan-R/boxr#32]
I get the following error after I run the follwing two lines of code (this package worked fine last week?)

require(boxr)
box_auth()

Reading client id from .Renviron
Reading client secret from .Renviron
Auto-refreshing stale OAuth token.
Error in refresh_oauth2.0(self$endpoint, self$app, self$credentials) : 
  client error: (400) Bad Request

**Comment by brendan-R** [comment]
Hello there,

Sorry about the delay in responding, I've been on the road for the last week or so.

Does the following work?

* Delete cached token file (probably at `~/.boxr-oauth`)
* Remove the lines beginning `BOX_CLIENT_SECRET=` and `BOX_CLIENT_ID=` from `~/.Renviron`
* In a fresh R session, run `library(boxr); box_auth()`

?
