### ISSUE TITLE
Interactive environment needed

### ISSUE THREAD

**Issue by terrytangyuan** [brendan-R/boxr#33]
Trying to use this function from command line but got this `Error: oauth_listener() needs an interactive environment`. It happens also when `interactive = FALSE`.

```
boxr::box_auth(
    client_id     = client_id,
    client_secret = client_secret,
    interactive = TRUE,
    write.Renv = FALSE
  )
```

**Comment by terrytangyuan** [comment]
Never mind! It's working now! Thanks for this useful package!

**Comment by brendan-R** [comment]
No worries, very glad you got it working! 💃
