### ISSUE TITLE
Issues in authenticating on a specific server.

### ISSUE THREAD

**Issue by sahilseth** [brendan-r/boxr#41]
first off, awesome package!

It is working well on two of my machines, but fails authentication on our HPCC server. I am trying to investigate the issue, but the error message seems generic.

Specially I see:

```
box_auth(interactive = TRUE)
Reading client id from .Renviron
Reading client secret from .Renviron
Auto-refreshing stale OAuth token.
Error in box_auth(interactive = TRUE) : 
  Login at box.com failed; unable to connect to API.
```

**further looking at the step at which it fails I see:**

```
Browse[2]> test_req
Response [https://api.box.com/2.0/folders/0]
  Date: 2016-01-29 19:41
  Status: 200
  Content-Type: application/json
  Size: 2.27 kB
No encoding supplied: defaulting to UTF-8.
```

**note**

Since a browser is not accessible, I have copied the .boxr-oauth from my personal machine to the HPCC.

**Comment by brendan-r** [comment]
Hey @sahilseth, glad you like the package!

Based on your report (thanks for the detail), my hunch is that your HPCC server has `httr v1.1.0`, which was released 3 days ago. As you got a 200 OK response back from the server, the authentication *is* successful. However, `httr` has gone from reporting this as `"success"` to `"Success"`, which unfortunately means that `boxr` doesn't understand. Thrilling stuff!

I've had the changes for the `httr v1.1.0` release ready in a branch (248bbfcf4df16f7a60cb10101f35df3b7910cae3) for a while; they're now merged to master, and I have begun the CRAN dance. 

I'd imagine that the latest version should be up on CRAN by the middle of next week. In the meantime, you can install `boxr v0.3.2` from GitHub with:

```r
# install.packages("devtools")
devtools::install_github("brendan-R/boxr")
```

`boxr v0.3.2` has a hard dependency on `httr >= v1.1.0`, so it should update it appropriately for you.

Let me know if that works!

Brendan

**Comment by brendan-r** [comment]
v0.3.2 on CRAN now -- let me know if `install.packages("boxr")` improves things.

**Comment by sahilseth** [comment]
Awesome! Thanks a lot brendan, after updating both packages (httr and boxr) from CRAN this works like a charm.

**Comment by brendan-r** [comment]
:+1:
