### ISSUE TITLE
box_fetch() seems to be limited maximum 100 files per directory

### ISSUE THREAD

**Issue by ijlyttle** [brendan-r/boxr#47]
Hi,

First to say that this is a lifesaver of a package, thanks!

I am finding a weird and difficult to reproduce error (due to all the side effects), but the upshot is this, if I have a box.com directory with more than 100 files, some of the files are ignored in a `box_fetch()` operation. The updater will show 1/100, ..., 100/100.

Have you come across this behavior?

Also, I realize there may be a box.com setting that I am not aware of, so I'll try to look around for such a thing.

Thanks for any light you can cast on the situation!

Thanks,

Ian

**Comment by ijlyttle** [comment]
Did some first digging - 

https://docs.box.com/reference#get-folder-info

seems that the call used in `box_ls()` is limited to 100 by default, but can be extended to 1000 - otherwise needs pagination.

If it's OK, I'll do a provisional PR to set default to 1000, but will ultimately need to use pagination.

Thoughts?

**Comment by brendan-r** [comment]
A PR would be much appreciated!

**Comment by ijlyttle** [comment]
Will do!

**Comment by brendan-r** [comment]
:+1: Thanks so much, you've been added as the package's first contributor! (b113ae56e2c58fbca59634cf86d9cfb226972c3a).

Agree that pagination is the way to solve this properly, thanks for offering to contribute it. I wrote a very simple pagination function for `box_search` [here](https://github.com/brendan-r/boxr/blob/master/R/boxr_search.R#L199-L231). If you think you can adapt/extend/genericize that, by all means do.

I think the improvements probably deserve a test. If you'd like to contribute one, shoot me a mail at foss@brendanrocks.com, and I'll send you the creds for the boxr account I use for testing (don't use your personal box account; it'll overwrite and delete everything several times!). However, if you can't spare the time to write a test of two, don't let that put you off.

**Comment by ijlyttle** [comment]
- Glad to contribute, as I've said before, this package is a lifesaver!
- Will be happy to take a stab at pagination, following your lead.
- I'll send a separate email to you to start the ball rolling on testing.

**Comment by ijlyttle** [comment]
fixed in  866f03b

**Comment by brendan-r** [comment]
:tada:
