### ISSUE TITLE
R crashes when using box_read_excel()

### ISSUE THREAD

**Issue by rlbarter** [brendan-r/boxr#49]
I'm trying to use `box_read_excel()` to load in a fairly small .xls file hosted on box. I don't get any errors but prints some output along the lines of:

`DEFINEDNAME: 07 b9 2b 08 7c 33 b2 83 88 f7 78 24 1c b5 f7 22 36 7e 10 43 a6 3b ff 5c 31 6b b4 a8 f2 0c`

and then R subsequently crashes (I assume that it is running out of memory, but the file itself is pretty small, say only 200 rows and 20 columns).

Do you have any idea about what is going wrong here? Sorry if this is a completely silly question!

**Comment by rlbarter** [comment]
Also for some context:

```{r}
sessionInfo()
# R version 3.3.2 (2016-10-31)
# Platform: x86_64-apple-darwin13.4.0 (64-bit)
# Running under: OS X El Capitan 10.11.6
```

**Comment by rlbarter** [comment]
Turns out that the printed output is a general issue regarding reading excel files into R, rather than a boxr-specific issue. See this [readxl issue](https://github.com/hadley/readxl/issues/82).

I'm still trying to figure out why R crashes though. I think the printed output and the crashing are two separate issues.

Apologies for the spammy issue!!

**Comment by brendan-r** [comment]
No worries, glad you tracked the source of the problem down. Hope you get to the bottom of it!
