### ISSUE TITLE
Error while fetching

### ISSUE THREAD

**Issue by Giannettig** [brendan-r/boxr#54]
Hi I am receiving this error while fetching files

 Error in class(out) <- "boxr_object_list" : 
  attempt to set an attribute on NULL

Any idea on what went wrong?

**Comment by brendan-r** [comment]
Sounds like a bug, probably in `box_ls` or `box_search` (which may be being called by another function). 

Can you remember (or see in your history) which function you were using when the error appeared?

Do you happen to know if the folder contained files, or if it was empty?

**Comment by Giannettig** [comment]
Hi I was using box fetch (the function supposed to download the whole
folder content).
I solved the issue by having saply iterate over the result of box_ls and
download the files one by one.

G.

2017-03-06 19:12 GMT+01:00 Brendan Rocks <notifications@github.com>:

**Comment by brendan-r** [comment]
Hm. That's no fun. Will investigate.

**Comment by EricKarsten** [comment]
I had the same issue. It would appear that box_fetch works on Box folders without subfolders, but not on those which contain subfolders.

**Comment by ijlyttle** [comment]
Does this work any better using the dev version?

It has a reworking of `box_ls()`

```r
# install.packages(devtools)
install_github("brendan-r/boxr")
```

**Comment by EricKarsten** [comment]
Yes @ijlyttle  I no longer see the issue using the dev version. Thanks for saving me from having to use the workaround!

**Comment by ijlyttle** [comment]
Great news! This may motivate getting a CRAN release out the door.
