### ISSUE TITLE
Can't authorize box, box.com layout has changed and no longer matches your instructions

### ISSUE THREAD

**Issue by ksbystrom** [brendan-r/boxr#57]
The website https://ea.app.box.com/developers/console doesn't match the instructions you have for setting up authorization for boxr at https://cran.r-project.org/web/packages/boxr/vignettes/boxr.html . Is there somewhere I can get up to date instructions?

**Comment by brendan-r** [comment]
Hey, sorry about this!

Did you figure it out in the end? If so, would you be willing to take a new screen grab (or tweak the instructions)?

**Comment by j450h1** [comment]
Do you happen to get this error in the web browser after you put in your client id and client secret after box_auth()?

```
Error: redirect_uri_mismatch

 Show Error Details
scope=
response_type=code
redirect_uri=http://localhost:1410/
state=jU0uqp7ER4
client_id=[MYCLIENTIDHERE]
```

**Comment by brendan-r** [comment]
@j450h1 Is that a question for me or for @ksbystrom ?

If it's a different bug-report / help request, would you be alright to make a separate issue, and include the commands used and a [traceback](https://stat.ethz.ch/R-manual/R-devel/library/base/html/traceback.html)? 

e.g.

```
> box_auth()
> *Error message*
> traceback()
> *Lots of detail about what went wrong where*
```

**Comment by j450h1** [comment]
Apologies. I will submit a separate issue.

**Comment by brendan-r** [comment]
@ksbystrom, thanks to @NathanCDay, the documentation is now updated! :tada:
