### ISSUE TITLE
Unclear how to use summary()

### ISSUE THREAD

**Issue by j450h1** [brendan-r/boxr#62]
```
box_push(dir_id = relevant_folder$id, local_dir = local_folder_path, overwrite = TRUE)
```

```
started at     : 2017-10-13 13:29:27 (took 2.39 hours)
6 files updated on box.com, 2 files were NOT updated on box.com.

Use summary() to see individual file operations.
```
Can you advise how I can use summary? Do I have to assign this function to a variable and then use summary on the individual items in the list?

**Comment by brendan-r** [comment]
> Do I have to assign this function to a variable and then use summary on the individual items in the list?

Yup!

**Comment by j450h1** [comment]
Great thanks!
