### ISSUE TITLE
Error in box_read() run in parallel

### ISSUE THREAD

**Issue by thisisnickb** [brendan-r/boxr#66]
I'm having some trouble reading in files in parallel via box_read(). 

When I use this code (R 3.4.2; boxr 0.3.4):

library(doParallel)
Sys.setenv(OMP_NUM_THREADS=parallel::detectCores())
registerDoParallel()
library(boxr)
box_auth()

exvec<-c("261477875891", "261483783671", "261482746699", "261484155439", "261489022298")

ex<-foreach(i=exvec, .combine = rbind) %dopar% box_read(i, read_fun=utils::read.delim, sep = "\t", fill=TRUE, quote=NULL, comment.char='', stringsAsFactors=FALSE)

I was at first able to read everything in cleanly, but now, all of a sudden I'm getting this message/a crash of my Rstudio:

Error in box_read(i, read_fun = utils::read.delim, sep = "\t", fill = TRUE,  : 
task 1 failed - "Bulk data encryption algorithm failed in selected cipher suite."

**Comment by ijlyttle** [comment]
I don't have any good answers for you, but maybe a question for now: does this work if you do not use parallel?

I did a google search on the error message "Bulk data encryption algorithm failed in selected cipher suite." - nothing definitive there, but the error seems happen, as it did for you, the *second* time the code is run.

**Comment by thisisnickb** [comment]
If I run the same code serially (replacing %dopar% with %do%), then the
code runs with no error (on both a first and second try).

**Comment by NathanCDay** [comment]
A lotta bit late, but does doing the download from Box in parallel help make it faster here?

It was my understanding the API limited users to a single simultaneously download, ala `box_fetch()` behavior.

**Comment by thisisnickb** [comment]
Ah - I didn't realize that.

Thanks,

-Nick

**Comment by ijlyttle** [comment]
It seems this is an API limitation, so closing (please re-open if you disagree)
