### ISSUE TITLE
Malformed DESCRIPTION file

### ISSUE THREAD

**Issue by pcarbo** [brendan-r/boxr#67]
I think a comma was missing when I tried to install from the master branch (commit fc4fb6a). See attached for corrected `DESCRIPTION` file.

[DESCRIPTION.gz](https://github.com/brendan-r/boxr/files/1684021/DESCRIPTION.gz)

**Comment by ijlyttle** [comment]
Thanks for pointing this out!

**Comment by ruaridhw** [comment]
FYI @ijlyttle this is still not fixed. #68 was closed, not merged.

**Comment by ijlyttle** [comment]
Gah! Merged now... thanks for letting me know!
