### ISSUE TITLE
Creating Box folders

### ISSUE THREAD

**Issue by nathancday** [brendan-r/boxr#69]
Is it possible to create a new folder on Box via this package?

I looked through the`NAMESPACE` and could only find `box_delete_folder()`. Is there a hidden internal function that does something like this?

I adore this package and would love to add that ability to my workflow, happy to help.

**Comment by nathancday** [comment]
the function is called `box_dir_create()` don't know how I didn't see it earlier.

**Comment by ijlyttle** [comment]
Sorry for not responding, as I have been swamped by other projects - but just to note that it is wonderful when an issue has already been solved!
