### ISSUE TITLE
Additional error in `box_pagination` when offset exceeds 300,000

### ISSUE THREAD

**Issue by awong234** [brendan-r/boxr#74]
Hello,

As my box folder contents exceed 300,000, I am running into additional HTTP 400 errors, which may be an issue of the Box API rather than `boxr`, but it should be made known anyway. 

When the offset is 300,001, `httr::GET()` operation fails with an HTTP 400 error; offset = 300,000 works just fine. Are there any ideas for what the solution may be?

**Comment by awong234** [comment]
Thanks, that's a handy function! It doesn't report why the GET fails.

## HTTP 200 OK
```
...
url$query$offset <- as.integer(300000)
req      <- httr::with_verbose({httr::GET(
  url, 
  httr::config(token = getOption("boxr.token"))
)})
-> GET /2.0/folders/48978104905/items?fields=name&limit=1000&offset=300000 HTTP/1.1
-> Host: api.box.com
-> User-Agent: libcurl/7.54.1 r-curl/2.8.1 httr/1.3.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> Authorization: Bearer khSt6bJ1o3UnRYdIQqf7nABnCBZ0cdKp
-> 
<- HTTP/1.1 200 OK
<- Date: Sun, 17 Jun 2018 17:43:22 GMT
<- Content-Type: application/json
<- Transfer-Encoding: chunked
<- Connection: keep-alive
<- Strict-Transport-Security: max-age=31536000
<- Cache-Control: no-cache, no-store
<- Content-Encoding: gzip
<- Vary: Accept-Encoding
<- BOX-REQUEST-ID: 0t2j2g7ro2a6kmo058357oetlge
<- Age: 5
<- 
```

## HTTP 400 Bad Request

```
...
url$query$offset <- as.integer(300001)
req      <- httr::with_verbose({httr::GET(
  url, 
  httr::config(token = getOption("boxr.token"))
)})

-> GET /2.0/folders/48978104905/items?fields=name&limit=1000&offset=300001 HTTP/1.1
-> Host: api.box.com
-> User-Agent: libcurl/7.54.1 r-curl/2.8.1 httr/1.3.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> Authorization: Bearer khSt6bJ1o3UnRYdIQqf7nABnCBZ0cdKp
-> 
<- HTTP/1.1 400 Bad Request
<- Date: Sun, 17 Jun 2018 17:44:10 GMT
<- Content-Type: application/json
<- Transfer-Encoding: chunked
<- Connection: keep-alive
<- Strict-Transport-Security: max-age=31536000
<- Cache-Control: no-cache, no-store
<- Content-Encoding: gzip
<- Vary: Accept-Encoding
<- BOX-REQUEST-ID: 0s2belfjb6ohli2bd64ru7gr7u0
<- Age: 0
<- 
```

The question has been posted at [box community](https://community.box.com/t5/Platform-and-Development-Forum/Maximum-offset/m-p/57816).

**Comment by ijlyttle** [comment]
It may not show the answer in this case, but it was useful to demonstrate that the URL was not formatted differently from the first case:

```
-> GET /2.0/folders/48978104905/items?fields=name&limit=1000&offset=300000 HTTP/1.1
```

to the second:

```
-> GET /2.0/folders/48978104905/items?fields=name&limit=1000&offset=300001 HTTP/1.1
```  

Hopefully, the box community can help!

**Comment by awong234** [comment]
Aha, the Box team says that offset-based paging has a maximum of 300,000.

>Hi Alec,
>
>My name is Matt with the box Technical Support team and I will be assisting you with this request. For offset-based paging, the maximum is 300,000. If you need to go beyond this we recommend to use marker-based paging. It looks like this limit is currently not noted in our online documentation, so I have suggested this be added. 
>
>Please let me know if you have any further questions. 
>Matt Behn
>Technical Support Engineer

Is there a utility for marker-based paging, or do you think we'll need to put one together?

**Comment by awong234** [comment]
Hello, 

I'm testing out a new method that saves the offset pagination method, but also adds marker pagination as the default, since "marker-based paging is the preferred method and is most performant" [ref](https://developer.box.com/reference#get-a-folders-items).
