### ISSUE TITLE
loading specific excel sheets from box using box_read

### ISSUE THREAD

**Issue by avierse** [brendan-r/boxr#81]
Hi Brandon,

This is a great package! I am, however, having trouble downloading a specific sheet from an excel book from Box.com. Is there a way in the package to specify which sheet you want to read instead of defaulting to sheet 1?

Thanks!

**Comment by nathancday** [comment]
So `box_read()` is calling a variety of different functions depending on the file type.

The help page `?box_read` shows what functions are being called for each file type and for XLSX files it is using `readxl::read_excel()`. It also shows that is is using the elipse, `...` to pass additional parameter to the reading function.

So any parameters that `read_xlsx()` accepts you can pass, including `sheet`.

```
xlsx_box_id <- 11111111111 # obviously fake
box_read(xlsx_box_id, sheet = 2)
```

**Comment by ijlyttle** [comment]
I'm assuming that @nathancday solved the issue.
