### ISSUE TITLE
Error: GDK_BACKEND does not match available displays

### ISSUE THREAD

**Issue by jhavumaki** [brendan-r/boxr#82]
I have SSH'ed into a HPC cluster and am running a remote interactive session of R (version 3.3.0).

I loaded the library, entered "box_auth()" and got prompted for my box client id and then box client secret. 

Terminal then hangs on the following output:

Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Error: GDK_BACKEND does not match available displays

It seems to work from terminal on my local machine where I have already previously authenticated my box account from Rstudio, so I imagine there is something e.g. software missing on the cluster? 

Any advice would be helpful. Thank you.

**Comment by ijlyttle** [comment]
The boxr package relies on httr to manage the oauth token - but box.com does not support the oauth "dance" for out-of-band authentication. I this case, I think you need to follow option (3) here:

https://support.rstudio.com/hc/en-us/articles/217952868-Generating-OAuth-tokens-for-a-server-using-httr

The idea is that you copy your local `.boxr-oauth` file to your remote environment.

It is critical that you have the same version of httr in your local R environment, where you generate the token, as your remote R environment, where you deploy the token,
