### ISSUE TITLE
box_ls() caps results at 1000 items?

### ISSUE THREAD

**Issue by nathancday** [brendan-r/boxr#83]
I ran into this, querying an ever expanding folder where I collect raw data files. It seems that `box_ls() %>% as.data.frame()` is truncating results at 1000 rows. Is this a known behavior? I couldn't find a reference to this in the documentation.

Happy to write some docs/code if this is a bug and not intended.

**Comment by nathancday** [comment]
I can't reproduce with the development version so am closing this

**Comment by ijlyttle** [comment]
This is a limitation overcome in the development version, see #47 - if I can find some time, I should make a CRAN release.

**Comment by nathancday** [comment]
I rely on this package for my daily work, so if you want some extra helpers I am happy to chip in.
